//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CityCell.ServiceCityCell {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceCityCell.IWSUser")]
    public interface IWSUser {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSUser/ObtenerLogin", ReplyAction="http://tempuri.org/IWSUser/ObtenerLoginResponse")]
        int ObtenerLogin(string UserLogin, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSUser/ObtenerLogin", ReplyAction="http://tempuri.org/IWSUser/ObtenerLoginResponse")]
        System.Threading.Tasks.Task<int> ObtenerLoginAsync(string UserLogin, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSUser/RegisterNow", ReplyAction="http://tempuri.org/IWSUser/RegisterNowResponse")]
        int RegisterNow(string Name, string NumIndentification, string Mail, string UserId, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSUser/RegisterNow", ReplyAction="http://tempuri.org/IWSUser/RegisterNowResponse")]
        System.Threading.Tasks.Task<int> RegisterNowAsync(string Name, string NumIndentification, string Mail, string UserId, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSUser/ObtenerProductos", ReplyAction="http://tempuri.org/IWSUser/ObtenerProductosResponse")]
        System.Data.DataSet ObtenerProductos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSUser/ObtenerProductos", ReplyAction="http://tempuri.org/IWSUser/ObtenerProductosResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> ObtenerProductosAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWSUserChannel : CityCell.ServiceCityCell.IWSUser, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSUserClient : System.ServiceModel.ClientBase<CityCell.ServiceCityCell.IWSUser>, CityCell.ServiceCityCell.IWSUser {
        
        public WSUserClient() {
        }
        
        public WSUserClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSUserClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSUserClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSUserClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int ObtenerLogin(string UserLogin, string Password) {
            return base.Channel.ObtenerLogin(UserLogin, Password);
        }
        
        public System.Threading.Tasks.Task<int> ObtenerLoginAsync(string UserLogin, string Password) {
            return base.Channel.ObtenerLoginAsync(UserLogin, Password);
        }
        
        public int RegisterNow(string Name, string NumIndentification, string Mail, string UserId, string Password) {
            return base.Channel.RegisterNow(Name, NumIndentification, Mail, UserId, Password);
        }
        
        public System.Threading.Tasks.Task<int> RegisterNowAsync(string Name, string NumIndentification, string Mail, string UserId, string Password) {
            return base.Channel.RegisterNowAsync(Name, NumIndentification, Mail, UserId, Password);
        }
        
        public System.Data.DataSet ObtenerProductos() {
            return base.Channel.ObtenerProductos();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ObtenerProductosAsync() {
            return base.Channel.ObtenerProductosAsync();
        }
    }
}
